[package]
name = "stopwatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
eframe = "0.26.2"
egui = "0.26.2"
env_logger = "0.11.3"
indexmap = "2.2.6"
